### ISSUE TITLE
script/download_and_untar.sh incompatible with zc.buildout installation

### ISSUE THREAD

**Issue by 1kastner** [bioidiap/bob.db.voxforge#3]
Like this the shell script does not work in case you used zc.buildout. Even the shell script is not shipped. I could use it and modified it for my purpose like this:
https://gist.github.com/1kastner/587ec3b395be715c3461
If it could be shipped in the normal bob buildout process and further adjusted for that, that could be great!

**Comment by siebenkopf** [comment]
Indeed, the script is a bit awkward, and it is usable only in a given setup (e.g., it is only working when the package is build itself, but not when it is used as an egg). Unfortunately, the directories are different for the different installation types (``zc.buildout``, ``mr.developer``, ``buildout`` and ``pip``).

Your solution is only working for one other case, but not generally. I am not even sure if there is a proper simple ``bash`` solution for that problem. However, I might come up with a ``python`` script to replace the current ``bash`` script that takes care of the directory issue.

**Comment by siebenkopf** [comment]
I have just pushed a ``python`` version of the script (https://github.com/bioidiap/bob.db.voxforge/commit/5e56ef57c58ef27fdd77192fe008945bc372b6dd), which uses ``pkg_resources`` to obtain the list file. With this it should be fixed now, as this script will automatically delete also incompletely downloaded files. Feel free to re-open in case of problems.

Note that the fix will be in place in the new version of ``bob.db.voxforge`` only. For the time being, you can use ``mr.developer`` in your ``buildout.cfg`` in order to get the latest version of the package from ``GitHub``.

**Comment by 1kastner** [comment]
Thank you very much for that, I got it working before but it will be
good for the next to come!

Am 29.12.2015 um 19:31 schrieb Manuel Günther (aka. Gunther, Guenther):
